apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  clusterIP: None
  selector:
    app: database
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: mongodb
